/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Final_demo1 */

#ifndef _Included_Final_demo1
#define _Included_Final_demo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Final_demo1
 * Method:    channelinfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Final1_demo1_channelinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
