/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo */

#ifndef _Included_demo
#define _Included_demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo
 * Method:    channel
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_Final_demo_channel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
